# This file was generated by GoReleaser. DO NOT EDIT.
class Encryptionverify < Formula
  desc "Cli to verify encryption v2"
  homepage ""
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/zduymz/encryptionverify/releases/download/v0.0.1/encryptionverify_0.0.1_Darwin_x86_64.tar.gz"
    sha256 "503071423bae7b48a97624e8b88682a84fa7292da896f58a5a4f864000b0f298"
  elsif OS.linux?
  end

  def install
    bin.install "encryptionverify"
  end

  test do
    system "#{bin}/encryptionVerfiy -version"
  end
end
