# This file was generated by GoReleaser. DO NOT EDIT.
class Xssh < Formula
  desc "Another SSH Wrapper"
  homepage "https://github.com/Apixio/xssh"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://repos.apixio.com/artifactory/homebrew//xssh/0.1.1/xssh_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "e037d10ef722218ea94f23929c25b374cfaf974a46c91d715e9bf02b094227bf"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://repos.apixio.com/artifactory/homebrew//xssh/0.1.1/xssh_0.1.1_linux_x86_64.tar.gz"
      sha256 "8d4ffa6f610b8f3ee58c1349e2ed7f3254bec0f28ef231c92761abf1160a5a99"
    end
  end

  def install
    bin.install "xssh"
  end

  test do
    system "#{bin}/xssh -v"
  end
end
